database:
  host: sql8.freesqldatabase.com
  port: 3306
  user: sql8800675
  password: dDPAwbBFk3
  database: sql8800675   # or hr depending on target schema

app:
  theme: light
  navbar_color: "#1f77b4"
